services:
  - type: web
    name: swiftbite-backend
    env: node
    rootDir: backend
    buildCommand: NODE_OPTIONS=--max_old_space_size=4096 npm install && NODE_OPTIONS=--max_old_space_size=4096 npm run build
    startCommand: npm start
    plan: free